### ISSUE TITLE
sys battery files (input_suspend) gets overwritten everytime value is changed manually

### ISSUE THREAD

**Issue by AnimeKittyFang** [crdroidandroid/android_device_xiaomi_alioth#3]
config : POCO F3 / Crdroid 10.5 / Rooted (magisk)

After installing Battery charge limit [root] apk and using it without success, I made a few tests.
I tried to limit battery charge directly setting /sys/class/power_supply/battery/input_suspend to 0 | 1
but whenever I change its value it goes back to its previous one within less a second.

Method to replicate : 
1) SET USB debugging On
2) Connect Phone to PC
3) Using CMD
  - `adb shell`
  - `su`

4) _if needed_
  - `mount -o rw,remount /`
  - `mount -o rw,remount /sys`
  - `mount -o ro,remount /`

5)
  - `cd /sys/class/power_supply/battery`
  - `cat input_suspend && echo 1 > input_suspend && cat input_suspend && sleep 1s && cat input_suspend`

Only way to force it is to use `chmod a-w input_suspend` right after echo, but that's not a good practice also knowing that doesn't help with using a third party tool to set it automatically.

Is there any way to prevent this happening ?

**Comment by gwolf2u** [comment]
use issue tracked or go in chat on telegram
